### ISSUE TITLE
agregar un handler del error en caso de que no sea uno de esos dos 

### ISSUE THREAD

**Issue by javierajorge** [javierajorge/epollcoroutinedoctest#6]
https://github.com/javierajorge/epollcoroutinedoctest/blob/7e0fa0949699d82542b4a13de012d82e6133b03f/include/block_syscall.hh#L34

**Comment by javierajorge** [comment]
Actualmente las blocksyscall invocan las llamadas a sistema y devuelven -1 cuando tuvieron algun problema, en caso de que el problema sea que necesita volver a intentar o la llamada esta bloqueada, la corrutina se suspende sin devovler el -1. Si el error es otro la corrutina continua, devuelve el -1 a quien la invoca y es este quien debe manejar el error.  Ejemplo 
https://github.com/javierajorge/epollcoroutinedoctest/blob/4ac38b69ab4a0a28ff0996582058c4cf46d5fc02/src/socket.cc#L73

@G10h4ck crees que esto esta bien o sería mejor que le pasemos un contenedor para una error condition en el constructor de la blocksiscall y que si no debe suspenderse en  
https://github.com/javierajorge/epollcoroutinedoctest/blob/7e0fa0949699d82542b4a13de012d82e6133b03f/include/block_syscall.hh#L34 se llame a la funcion bubleor exit ? 
Con esa nueva implementacion por defecto todas las llamadas a systema fallidas terminarian aboratando el programa y en caso de que el constructor de la blocksyscall reciba un lugar donde infomar el error se colocque alli el error y se devuelva el -1 y quien la invoca maneja el error.

**Comment by G10h4ck** [comment]
Correcto, tal como lo hablamos el otro dia ;)
