### ISSUE TITLE
armar una rama en el fork de libremesh

### ISSUE THREAD

**Issue by javierajorge** [javierajorge/epollcoroutinedoctest#7]
poner un modulito

**Comment by javierbrk** [comment]
https://github.com/javierbrk/lime-packages/blob/6ff111c8e4e924aa8a75b974a34e2d090fb0e8a6/packages/shared-state-async-server/Makefile

**Comment by javierbrk** [comment]
ya esta el makefile en el fork... no hice una rama para eso.
